// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvzLcvPjYynMyGreGloH9SVq0xnKVauRg',
    appId: '1:96225554793:web:64eb263d18d087ef95cdf8',
    messagingSenderId: '96225554793',
    projectId: 'mindfullapp-48c7f',
    authDomain: 'mindfullapp-48c7f.firebaseapp.com',
    storageBucket: 'mindfullapp-48c7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZtN2DhYMOeGdmQlkM_y0m5bpqhS4n9l0',
    appId: '1:96225554793:android:102da1e0482a4dcf95cdf8',
    messagingSenderId: '96225554793',
    projectId: 'mindfullapp-48c7f',
    storageBucket: 'mindfullapp-48c7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNiO4XYUN-yYj39ecYFB_LdMypmi_4BJc',
    appId: '1:96225554793:ios:06b998a8345e17d295cdf8',
    messagingSenderId: '96225554793',
    projectId: 'mindfullapp-48c7f',
    storageBucket: 'mindfullapp-48c7f.appspot.com',
    iosBundleId: 'com.example.mindfulMomentum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNiO4XYUN-yYj39ecYFB_LdMypmi_4BJc',
    appId: '1:96225554793:ios:06b998a8345e17d295cdf8',
    messagingSenderId: '96225554793',
    projectId: 'mindfullapp-48c7f',
    storageBucket: 'mindfullapp-48c7f.appspot.com',
    iosBundleId: 'com.example.mindfulMomentum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvzLcvPjYynMyGreGloH9SVq0xnKVauRg',
    appId: '1:96225554793:web:177a26455257944195cdf8',
    messagingSenderId: '96225554793',
    projectId: 'mindfullapp-48c7f',
    authDomain: 'mindfullapp-48c7f.firebaseapp.com',
    storageBucket: 'mindfullapp-48c7f.appspot.com',
  );
}
